### ISSUE TITLE
Blocks Randomly Missing in Survival

### ISSUE THREAD

**Issue by Supermath101** [feather-rs/feather#351]
In commit `4c34e17` on branch `main`, Cargo target `release`, Rust toolchain `nightly-x86_64-unknown-linux-gnu`, when setting the gamemode to survival and `level` to `trace` with an otherwise default `config.toml`, and after breaking at least one block, a few randomly positioned block aren't there on login-logout-login. You can logout then log back in as many times as you want and a different set of random blocks are missing. I have no idea how to precisely reproduce this.

**Comment by caelunshun** [comment]
This happens because survival-mode block breaking isn't implemented properly; the server thinks the player has insta-break. As a result, blocks that were clicked at all are considered broken.

> You can logout then log back in as many times as you want and a different set of random blocks are missing.

I can't seem to reproduce this part—the set of missing blocks remains the same after relogging.

**Comment by amberkowalski** [comment]
I'm happy to report this issue is fixed! Because... I removed the temporary block breaking logic :)

**Comment by Molive-0** [comment]
Can confirm this appears to be fixed. The block break speed is still incorrect however
